my_string = input('Введённый текст: ')
#print(len(my_string))
print(my_string.upper())
print(my_string.upper().lower())
print(my_string.replace( ' ' , ''))
print(my_string [1])
print(my_string [-1])